### ISSUE TITLE
Crash on Launch - NoClassFoundDefError

### ISSUE THREAD

**Issue by ScottoMotto** [CJMinecraft01/Multimeters#1]
Minecraft 1.12.2
Forge 2784 (also tried 2772 which you built against)
Fairly slim modpack - Immersive Engineering, Forestry, QOL mods.

Crash report
https://pastebin.com/gU5eUb5f

**Comment by CJMinecraft01** [comment]
Yep, just noticed the problem in the code. I'll take a look and push an update as soon as I can

**Comment by CJMinecraft01** [comment]
I've just tried to recreate the problem and have found a different problem which seems to be happening with CJCore. This is strange!

**Comment by CJMinecraft01** [comment]
I think I've fixed it now. I'll push the update

**Comment by CJMinecraft01** [comment]
Should be fixed in the latest version

**Comment by ScottoMotto** [comment]
Yes, it loads and works now. Cool idea. Trying it on various TEs and multiblocks.

**Comment by CJMinecraft01** [comment]
Let me know if you have any further issues.
